version: "3.3"
services:
  todo-server:
    image: todo-server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=testdb
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=testdb"]
      interval: 10s
      timeout: 5s
      retries: 5